SECRET_KEY='onlineweeklyreport'
SQLALCHEMY_TRACK_MODIFICATIONS=True
REPORT_DAY=0 #Monday how to change this?
SQLALCHEMY_DATABASE_URI='mysql://super:weeklyreport@10.208.133.197/weeklyreport'
SQLALCHEMY_POOL_RECYCLE = 499
SQLALCHEMY_POOL_TIMEOUT = 15